### ISSUE TITLE
Wrong POCO libraries order in pre-built TCJS for Linux

### ISSUE THREAD

**Issue by akoptelov** [hcl-pnp-rtist/lib-tcp-server#2]
When a static linking is used, the order of libraries passed to the linker is important. When an object from a library doesn't define any symbols known so far, it is skipped. So if there are other objects from other library that comes after it that have such symbols, they will be unresolved.

This library does not use libPocoFoundation directly, so its objects will be skipped. On the contrary, libPocoNet and libPocoJSON do, but by the time their objects get to the linker it is too late.

**Comment by elena-volkova-hcl** [comment]
Fixed.
Now linked libraries for POCO are specified only in pocoLib.tcjs and in correct order: PocoJSON, PocoNet, PocoFoundation
